encyclopedia/urls.py
from django.urls import path

from . import views



app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:TITLE>", views.entry_page, name="TITLE"),
    path("add", views.new_page, name="add"),
    path("edit", views.edit, name="edit"),
    path("random", views.random, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render,redirect
from random import choice
import markdown2

from .util import get_entry,list_entries, save_entry


def index(request): 
    """
    Render a view for Index page, if no query exist.
    Redirect to an Entry page, if a query matches an existing entry.
    Render a Search page, if a query does not match any entry.
    """

    # Check if there is a query else open the index page.
    if len(request.GET) > 0 :
        query = request.GET["q"].strip()
        new_entries = set()
        if len(query) > 0:
            entries = list_entries()
            for entry in entries:
                if query.lower() in entry.lower():
                    # List of entries that have the query as a substring.
                    new_entries.add(entry)

                if query.lower() == entry.lower():
                    # Redirect to entry's page.
                    return redirect("wiki:TITLE",TITLE=query)
        return render(request, "encyclopedia/search.html", {
        "new_entries": new_entries
        })

    else:
        return render(request, "encyclopedia/index.html", {
            "entries": list_entries()
    })

def entry_page(request,TITLE):
    """
    Render an Entry page, if the 'TITLE' matches an encyclopedia entry.
    Else, render an Error page.
    """
    entry = get_entry(TITLE)
    if entry:
        entry_titles = list_entries()
        for entry_title in entry_titles:
            if entry_title.lower() == TITLE.lower():
                TITLE = entry_title
                break
        html_entry = markdown2.markdown(entry)
        return render(request, "encyclopedia/entrypage.html", {
            "html_entry": html_entry,
            "entry": entry, 
            "title": TITLE
        })
    else:
        # Error page
        return render(request, "encyclopedia/errorpage.html", {
            "error": 'Page Not Found'
        })


def new_page(request):
    """
    Render a page where a user can create a new encyclopedia entry.
    Error checking if an encyclopedia entry already exists with the provided title, and
    Error checking if the user submit an empty form.
    Otherwise, save the encyclopedia entry to disk, and redirect to the new entry's page.
    """
    if request.method == "POST":
        title = request.POST["title"].strip()
        content = request.POST["content"]
        entries = list_entries()
        for entry in entries:
            if entry.lower() == title.lower():
                error1 = f"Your  Title '{title}' already exist!"
                return render(request, "encyclopedia/newpage.html", {
                    "error1": error1
                })
        if len(title) > 0 and len(content) > 0:
            save_entry(title,content)
            return redirect("wiki:TITLE",TITLE=title)
        else:
            error2 = "Please enter both a Title and it's Markdown Content!"
            return render(request, "encyclopedia/newpage.html", {
                    "error2": error2
                })
    else:
        return render(request, "encyclopedia/newpage.html")


def edit(request):
    """
    Edit a Markdown content and redirect to the content's page after been saved.
    """
    if request.method == "POST":
        title = request.POST["title"]
        content = request.POST["content"]
        if len(request.POST) > 3:
            if len(content) > 0:
                save_entry(title,content)
                return redirect("wiki:TITLE",TITLE=title)
            else:
                error = "Markdown Content connot be empty!"
                return render(request, "encyclopedia/editpage.html", {
                        "error": error,
                        "title": title,
                        "content": content
                    })
        return render(request, "encyclopedia/editpage.html", {
            "title": title,
            "content": content
        })


def random(request):
    """
    Redirect to a random Entry Page.
    """
    ramdom = choice(list_entries())
    return redirect("wiki:TITLE",TITLE=ramdom) 

encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <p><b>Title: {{ title }}</b></p>
    <div>
        {% if error %}<div class="alert alert-danger" role="alert">{{ error }}</div>{% endif %}

        <form action="{% url 'wiki:edit' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="title" value="{{ title }}">
            <label>Edit markdown content:</label>
            <br>
            <textarea autofocus name="content">{{ content }}</textarea>
            <br>
            <input type="hidden" name="save" value="save">
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/entrypage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <div>
        {{ html_entry | safe  }}
    </div>
    <form action="{% url 'wiki:edit' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{ title }}">
        <input type="hidden" name="content" value="{{ entry }}">
        <button type="submit" class="btn btn-warning">Edit</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/errorpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error Page
{% endblock %}

{% block body %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:TITLE' TITLE=entry %}" >{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}
    {% if error1 %}<div class="alert alert-danger" role="alert">{{ error1 }}</div>{% endif %}
    
    {% if error2 %}<div class="alert alert-danger" role="alert">{{ error2 }}</div>{% endif %}
    
    <h2>Create New Page</h2>
    <form action="{% url 'wiki:add' %}" method="post">
        {% csrf_token %}
        <label>Title:</label> <input type="text" name="title" placeholder="Title">
        <br>
        <label>Markdown content</label> <br> <textarea name="content"></textarea>
        <br>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Page
{% endblock %}

{% block search %}
    <form>
        <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
    </form>
{% endblock %}

{% block body %}
    <h2>Search results</h2>
    <ul>
        {% for entry in new_entries %}
            <li><a href="{% url 'wiki:TITLE' TITLE=entry %}" >{{ entry }}</a></li>
        {% empty %}
            <li>No result found</li>
        {% endfor %}
    </ul>          
{% endblock %}